name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET 8.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish IkSound/IkSound/IkSound.csproj -c Release -o release --nologo

    - name: List Files
      run: ls
    
    # changes the base-tag in index.html from '/' to 'IkSound' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to IkSound
      run: sed -i 's/<base href="\/" \/>/<base href="\/IkSound\/" \/>/g' release/wwwroot/index.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
